# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
    # build:
    #     runs-on: ubuntu-latest

    #     strategy:
    #         matrix:
    #             node-version: [14.x, 16.x, 18.x]
    #             # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #     steps:
    #         - uses: actions/checkout@v3
    #         # - run: npm install && npm install --prefix client
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #               cache: "npm"
    #         - run: npm ci
    #         - run: npm test
    #         # - run: npm run build --if-present

    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl ssh console --command "docker system prune --force" --app fly-builder-restless-darkness-1142
            - run: flyctl deploy --remote-only
